#!/usr/bin/env python3
"""Pre-commit hook: ensure Alembic migration is staged when SQLAlchemy models change.

Improved check:
- If staged files include model changes, run `alembic revision --autogenerate` to produce
  a temporary migration file.
- If the autogenerated migration contains schema operations (e.g. `op.create_table`, `op.add_column`),
  require at least one staged migration under `backend/alembic/versions/`.
- The autogenerated file is removed after the check.

This is a best-effort safety check and should not replace manual review.
"""
import sys
import subprocess
import os
import glob
import time


def get_staged_files():
    res = subprocess.run(["git", "diff", "--name-only", "--cached"], capture_output=True, text=True)
    if res.returncode != 0:
        print("Unable to get staged files", file=sys.stderr)
        sys.exit(0)
    return [p.strip() for p in res.stdout.splitlines() if p.strip()]


def list_versions_files():
    pattern = os.path.join("backend", "alembic", "versions", "*.py")
    return set(glob.glob(pattern))


def run_alembic_autogenerate():
    # Run alembic to generate a temporary revision. It will create a file under backend/alembic/versions/.
    # We pass a unique message to find the file.
    msg = f"autogen-check-{int(time.time())}"
    res = subprocess.run(["alembic", "-c", "backend/alembic.ini", "revision", "--autogenerate", "-m", msg], capture_output=True, text=True)
    return res


def find_new_generated_file(before, after):
    new = after - before
    if not new:
        return None
    # return the newest file by mtime among new files
    newest = max(new, key=lambda p: os.path.getmtime(p))
    return newest


def contains_schema_ops(path):
    try:
        text = open(path, "r", encoding="utf-8").read()
    except Exception:
        return False
    keywords = ["op.create_table", "op.add_column", "op.drop_table", "op.drop_column", "op.alter_column", "batch_alter_table", "sa.Column"]
    return any(k in text for k in keywords)


def main():
    staged = get_staged_files()
    if not staged:
        sys.exit(0)

    model_paths = [p for p in staged if p.startswith("backend/app/") and ("model" in p or p.endswith("models.py"))]
    if not model_paths:
        sys.exit(0)

    # If alembic isn't available, fall back to the older heuristic
    try:
        before = list_versions_files()
        res = run_alembic_autogenerate()
    except FileNotFoundError:
        # alembic not installed; fallback
        alembic_staged = [p for p in staged if p.startswith("backend/alembic/versions/")]
        if alembic_staged:
            sys.exit(0)
        print("\nWARNING: Alembic not available in environment. Falling back to basic check.")
        print("Detected model changes but no staged migration found under backend/alembic/versions/.")
        print("Run: make alembic-rev NAME=\"short-description\"")
        sys.exit(1)

    if res.returncode != 0:
        # Alembic failed; don't block commit but warn
        print("\nWARNING: Alembic autogenerate failed. Please ensure Alembic is configured locally.")
        print(res.stderr)
        # fallback to previous heuristic
        alembic_staged = [p for p in staged if p.startswith("backend/alembic/versions/")]
        if alembic_staged:
            sys.exit(0)
        print("Detected model changes but no staged migration found under backend/alembic/versions/.")
        print("Run: make alembic-rev NAME=\"short-description\"")
        sys.exit(1)

    after = list_versions_files()
    new_file = find_new_generated_file(before, after)
    if not new_file:
        # nothing generated; allow commit
        sys.exit(0)

    try:
        if not contains_schema_ops(new_file):
            # autogenerate produced no schema ops -> nothing to require
            os.remove(new_file)
            sys.exit(0)

        # autogenerate produced schema ops; require staged migration file
        alembic_staged = [p for p in staged if p.startswith("backend/alembic/versions/")]
        if alembic_staged:
            # clean up generated file
            os.remove(new_file)
            sys.exit(0)

        print("\nERROR: Alembic autogenerate detected schema changes but no staged migration was found.")
        print("Autogenerated sample (saved to %s) shows operations that should be captured in a migration." % new_file)
        print("Run locally: make alembic-rev NAME=\"short-description\" then review and stage the generated file under backend/alembic/versions/.")
        sys.exit(1)
    finally:
        # ensure removal of the autogenerated file if it still exists
        try:
            if os.path.exists(new_file):
                os.remove(new_file)
        except Exception:
            pass


if __name__ == '__main__':
    main()
